name: CI

on: [push]

jobs:
  test-linux:

    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        compiler: [dmd, ldc, dmd-beta, ldc-beta]

    steps:
    - uses: actions/checkout@v1
      # with:
      #   submodules: true

    - name: download-tf
      run: |
        mkdir -p download
        cd download
        wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.15.0.tar.gz
        tar xvf libtensorflow-cpu-linux-x86_64-1.15.0.tar.gz

    - name: test
      run: |
        source $(curl https://dlang.org/install.sh | bash -s -- ${{ matrix.compiler }} -a)
        LIBRARY_PATH=`pwd`/download/lib
        LD_LIBRARY_PATH=`pwd`/download/lib
        dub test --parallel -b=unittest-cov

    - name: codecov
      if: ${{ matrix.compiler == 'dmd' }}
      run: bash <(curl -s https://codecov.io/bash)


  test-windows:

    runs-on: windows-2019

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        compiler: [dmd]

    steps:
    - uses: actions/checkout@v1
      # with:
      #   submodules: true

    - name: download-tf
      run: |
        curl "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.15.0.zip" -o libtensorflow-cpu-windows-x86_64-1.15.0.zip
        7z x libtensorflow-cpu-windows-x86_64-1.15.0.zip
        cp lib/* .

    - name: test-dmd
      if: ${{ matrix.compiler == 'dmd' }}
      run: |
        curl "http://downloads.dlang.org/releases/2020/dmd.2.091.1.windows.7z" -o dmd.2.091.1.windows.7z
        7z x dmd.2.091.1.windows.7z
        dmd2/windows/bin64/dub test --parallel -b=unittest-cov
