name: linux

on: [push]

jobs:
  test:

    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        compiler: [dmd, ldc, dmd-beta, ldc-beta]

    steps:
    - uses: actions/checkout@v1

    - name: download-tf
      run: |
        mkdir -p download
        cd download
        wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.15.0.tar.gz
        tar xvf libtensorflow-cpu-linux-x86_64-1.15.0.tar.gz
        mv lib/libtensorflow* ..

    - name: test
      run: |
        source $(curl https://dlang.org/install.sh | bash -s -- ${{ matrix.compiler }} -a)
        dub test --parallel -b=unittest-cov

    - name: codecov
      if: ${{ matrix.compiler == 'dmd' }}
      run: bash <(curl -s https://codecov.io/bash)
