name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        compiler: [dmd, ldc, dmd-beta, ldc-beta]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: apt
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq -y gcc wget protobuf-compiler libprotobuf-dev libprotoc-dev libclang-6.0-dev
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libclang-6.0.so /usr/lib/libclang.so

    - name: make
      run: |
        source $(curl https://dlang.org/install.sh | bash -s -- ${{ matrix.compiler }} -a)
        dub fetch dpp
        make -j

    - name: test
      run: |
        source $(curl https://dlang.org/install.sh | bash -s -- ${{ matrix.compiler }} -a)
        make test
