name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-18.04

    strategy:
      max-parallel: 20
      matrix:
        compiler: [dmd, ldc]

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq -y gcc libprotobuf-dev wget
    - name: test
      run: |
        source $(curl https://dlang.org/install.sh | bash -s -- ${{ matrix.compiler }} -a)
        dub fetch dpp
        make test -j
