name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        compiler: [dmd, ldc, dmd-beta, ldc-beta]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: download
      run: make download/include/tensorflow/c/c_api.h

    - name: test
      run: |
        source $(curl https://dlang.org/install.sh | bash -s -- ${{ matrix.compiler }} -a)
        LIBRARY_PATH=`pwd`/download/lib
        LD_LIBRARY_PATH=`pwd`/download/lib
        dub test --parallel -b=unittest-cov

    - name: codecov
      if: ${{ matrix.compiler == 'dmd' }}
      run: bash <(curl -s https://codecov.io/bash)
