name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-18.04

    strategy:
      max-parallel: 20
      matrix:
        compiler: [dmd, ldc]

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq -y gcc wget protobuf-compiler libprotobuf-dev libprotoc-dev libclang-6.0-dev
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libclang-6.0.so /usr/lib/libclang.so
    - name: test
      run: |
        source $(curl https://dlang.org/install.sh | bash -s -- ${{ matrix.compiler }} -a)
        dub fetch dpp
        make test
